[build]
command = "hugo && npx tailwindcss -i ./static/css/style.css -o ./static/css/output.css"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.111.3"  # Use the latest Hugo version
HUGO_ENV = "production"
