[build]
  command = "hugo mod tidy && hugo --gc --minify && npx tailwindcss -i ./static/css/style.css -o ./static/css/output.css"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"

